from django.shortcuts import redirect
from django.urls import path

from .views import (
    StudyLoginView,
    StudyLogoutView,
    dashboard_view,
    study_lab_view,
    assessment_center_view,
    focus_zone_view,
    analytics_view,
    guardian_connect_view,
    parent_presence_event_view,
    save_session_view,
    send_test_parent_whatsapp_view,
    send_parent_update_view,
    signup_view,
    twilio_whatsapp_status_callback_view,
    update_parent_contact_view,
    update_theme_view,
    upload_document_view,
    generate_mcq_view,
    submit_test_view,
    ask_study_ai_view,
    clear_study_ai_view,
)

urlpatterns = [
    path("", lambda r: redirect("dashboard")),
    path("dashboard/", dashboard_view, name="dashboard"),
    path("study-lab/", study_lab_view, name="study_lab"),
    path("assessment/", assessment_center_view, name="assessment_center"),
    path("focus/", focus_zone_view, name="focus_zone"),
    path("analytics/", analytics_view, name="analytics"),
    path("guardian/", guardian_connect_view, name="guardian_connect"),
    path("login/", StudyLoginView.as_view(), name="login"),
    path("logout/", StudyLogoutView.as_view(), name="logout"),
    path("signup/", signup_view, name="signup"),
    path("ask-ai/", ask_study_ai_view, name="ask_study_ai"),
    path("clear-ai/", clear_study_ai_view, name="clear_study_ai"),
    path("document/upload/", upload_document_view, name="upload_document"),
    path("test/generate/", generate_mcq_view, name="generate_mcq"),
    path("test/submit/", submit_test_view, name="submit_test"),
    path("sessions/save/", save_session_view, name="save_session"),
    path("parents/presence/", parent_presence_event_view, name="parent_presence_event"),
    path("parents/update/", update_parent_contact_view, name="update_parent_contact"),
    path("parents/send/", send_parent_update_view, name="send_parent_update"),
    path("parents/test/", send_test_parent_whatsapp_view, name="send_test_parent_whatsapp"),
    path("twilio/whatsapp/status/", twilio_whatsapp_status_callback_view, name="twilio_whatsapp_status_callback"),
    path("theme/update/", update_theme_view, name="update_theme"),
]
